### ISSUE TITLE
UI Display of Data

### ISSUE THREAD

**Issue by mshoote** [jakeharding/repo-health#62]
On the UI when using the application the fields "Open Issues Last Year" & "PR's last year" is just an array of values. If possible a good addition would to format it so the user could see more clearly that each value correlated with a specific month. Either using a simple table or graph one could display this data and it would be more quickly interpreted and pleasing to the user.

**Comment by jakeharding** [comment]
I just merged the charts into the dev branch. Let us know what you think!

**Comment by mshoote** [comment]
Will do, and question, to update my clone with those changes should I re-clone the repo or can I just do a pull and get the charts piece?

**Comment by bparish628** [comment]
You would probably have to do a `git checkout -b origin/dev` to use the dev branch, since a clone is master

**Comment by mshoote** [comment]
I went to the root folder of repo health and ran the git checkout -b origin/dev and it said
Switched to a new branch 'origin/dev'

Then I ran docker-compose up and tried both cakephp/cakephp and django/django but didn't see any charts appear I may be missing a step or need to look into it more, any thoughts on what i may have done wrong?

**Comment by bparish628** [comment]
The docker container will still have the old code since it is self contained. So you will have to have to do a `./docker/clean.sh` and then do a `docker-compose up` again :confused:.

**Comment by jakeharding** [comment]
You may have created a local branch called `origin/dev`.  Run `git branch` to list your local branches and delete it if it is there. Run `git checkout -b dev origin/dev` to create a dev branch on your local and have it track the origin dev branch.

**Comment by mshoote** [comment]
Matthews-MacBook-Pro:repo-health matthewschuette$ git branch
  master
* origin/dev


It looks like it did. So I will try to re checkout the way you said and then re run the clean.sh and compose up.

**Comment by mshoote** [comment]
I tried what you said Jake and it updated the UI however I did not see any charts on any of the 3 tabs (Details, PR's, Issue). Do you think I should just do a fresh clone of dev?

**Comment by jakeharding** [comment]
Try to clear the cache in your browser and reload the page.  In Chrome, I think you hold control and click reload.
